// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package categoryQuerier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOne(ctx context.Context, arg CreateOneParams) (Category, error)
	DeleteOne(ctx context.Context, id uuid.UUID) error
	GetMany(ctx context.Context, arg GetManyParams) ([]Category, error)
	GetManyByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Category, error)
	GetOneById(ctx context.Context, id uuid.UUID) (Category, error)
	UpdateOneById(ctx context.Context, arg UpdateOneByIdParams) (Category, error)
}

var _ Querier = (*Queries)(nil)
